version: 0.2

env:
  variables:
    PLACEHOLDER_ENV_VAR: "TODO"
  parameter-store:
    DOCKER_USERNAME: /docker/username
    DOCKER_PASSWORD: /docker/password

phases:
  pre_build:
    commands:
      - echo Logging into DockerHub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo "Deploying API backend Lambda function..."
      - cd api
      - sam build --use-container
      - sam deploy --s3-bucket $S3_ARTIFACTS_BUCKET_NAME
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files: imagedefinitions.json
